# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
