# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_tracker', '0003_auto_20170603_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='truck_pic',
        ),
        migrations.AddField(
            model_name='image',
            name='truck_pic',
            field=models.ManyToManyField(related_name='images', to='truck_tracker.Truck'),
        ),
    ]
