# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_tracker', '0004_auto_20170604_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='truck_pic',
        ),
        migrations.AddField(
            model_name='truck',
            name='document',
            field=models.FileField(default='null', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
